version: 2.1
jobs:
    build:
        working_directory: ~/lacios
        docker:
            - image: circleci/node:12.9.0            
        steps:
            - checkout
            - run:
                  name: update-npm
                  command: "sudo npm install -g npm@latest"
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                  name: install-npm-wee
                  command: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules           
            - run:
                  name: test
                  command: |                        
                        sudo npm install -g --unsafe-perm now
                        sudo npm install wait-on -g
                        npm run start:ci
                        npm run test:ci          
            - store_artifacts:
                  path: coverage      
            - store_test_results:
                  path: coverage