module.exports = {
    users: [{
        email: "iron-man@marvel.ca",
        password: "password",
        first_name: "tony",
        last_name: "stark"
    }, {
        email: "cap@marvel.ca",
        password: "password",
        first_name: "steve",
        last_name: "rogers"
    }, {
        email: "thor@marvel.ca",
        password: "password",
        first_name: "thor",
        last_name: "odinson"
    }, {
        email: "hulk@marvel.ca",
        password: "password",
        first_name: "bruce",
        last_name: "banner"
    }, {
        email: "blackwidow@marvel.ca",
        password: "password",
        first_name: "natasha",
        last_name: "romanoff"
    }, {
        email: "hawkeye@marvel.ca",
        password: "password",
        first_name: "clint",
        last_name: "barton"
    }, {
        email: "spider-man@marvel.ca",
        password: "password",
        first_name: "peter",
        last_name: "parker"
    }, {
        email: "marvel@marvel.ca",
        password: "password",
        first_name: "carol",
        last_name: "danvers"
    }, {
        email: "falcon@marvel.ca",
        password: "password",
        first_name: "sam",
        last_name: "wilson"
    }, {
        email: "wintersoldier@marvel.ca",
        password: "password",
        first_name: "bucky",
        last_name: "barnes"
    }, {
        email: "drstrange@marvel.ca",
        password: "password",
        first_name: "stephen",
        last_name: "strange"
    }, {
        email: "venom@marvel.ca",
        password: "password",
        first_name: "eddie",
        last_name: "brock"
    }, {
        email: "cyclops@marvel.ca",
        password: "password",
        first_name: "scott",
        last_name: "summers"
    }, {
        email: "storm@marvel.ca",
        password: "password",
        first_name: "ororo",
        last_name: "munro"
    }, {
        email: "phoenix@marvel.ca",
        password: "password",
        first_name: "jean",
        last_name: "grey"
    }, {
        email: "cable@marvel.ca",
        password: "password",
        first_name: "nathan",
        last_name: "summers"
    }, {
        email: "doom@marvel.ca",
        password: "password",
        first_name: "victor",
        last_name: "von doom"
    }, {
        email: "ghost@marvel.ca",
        password: "password",
        first_name: "gwen",
        last_name: "stacy"
    }, {
        email: "lukecage@marvel.ca",
        password: "password",
        first_name: "luke",
        last_name: "cage"
    }, {
        email: "jessicajones@marvel.ca",
        password: "password",
        first_name: "jessica",
        last_name: "jones"
    }, {
        email: "kingpin@marvel.ca",
        password: "password",
        first_name: "wilson",
        last_name: "fisk"
    }, {
        email: "daredevil@marvel.ca",
        password: "password",
        first_name: "matthew",
        last_name: "murdock"
    }, {
        email: "humantorch@marvel.ca",
        password: "password",
        first_name: "johnny",
        last_name: "storm"
    }, {
        email: "antman@marvel.ca",
        password: "password",
        first_name: "scott",
        last_name: "lang"
    }, {
        email: "wasp@marvel.ca",
        password: "password",
        first_name: "janet",
        last_name: "van dyne"
    }, {
        email: "ultron@marvel.ca",
        password: "password",
        first_name: "hank",
        last_name: "pym"
    }, {
        email: "namor@marvel.ca",
        password: "password",
        first_name: "imperius",
        last_name: "rex"
    }, {
        email: "blackbolt@marvel.ca",
        password: "password",
        first_name: "blackagar",
        last_name: "boltagon"
    }, {
        email: "fantastic@marvel.ca",
        password: "password",
        first_name: "reed",
        last_name: "richards"
    }, {
        email: "deadpool@marvel.ca",
        password: "password",
        first_name: "wade",
        last_name: "wilson"
    }, {
        email: "thing@marvel.ca",
        password: "password",
        first_name: "ben",
        last_name: "grimm"
    }, {
        email: "invisible@marvel.ca",
        password: "password",
        first_name: "susan",
        last_name: "storm"
    }, {
        email: "spider-woman@marvel.ca",
        password: "password",
        first_name: "jessica",
        last_name: "drew"
    }, {
        email: "blackcat@marvel.ca",
        password: "password",
        first_name: "felicia",
        last_name: "hardy"
    }, {
        email: "havoc@marvel.ca",
        password: "password",
        first_name: "alex",
        last_name: "summers"
    }, {
        email: "starlord@marvel.ca",
        password: "password",
        first_name: "peter",
        last_name: "quill"
    }, {
        email: "nova@marvel.ca",
        password: "password",
        first_name: "richard",
        last_name: "ryder"
    }, {
        email: "warlock@marvel.ca",
        password: "password",
        first_name: "adam",
        last_name: "warlock"
    }, {
        email: "shadowcat@marvel.ca",
        password: "password",
        first_name: "kitty",
        last_name: "pryde"
    }, {
        email: "magik@marvel.ca",
        password: "password",
        first_name: "illyana",
        last_name: "rasputin"
    }, {
        email: "iceman@marvel.ca",
        password: "password",
        first_name: "bobby",
        last_name: "drake"
    }, {
        email: "beast@marvel.ca",
        password: "password",
        first_name: "hank",
        last_name: "mccoy"
    }, {
        email: "angel@marvel.ca",
        password: "password",
        first_name: "warren",
        last_name: "worthington"
    }],
    pages: [{
        name: "some page",
        description: "some description"
    }]
}